//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class tblUsers
    {
        public int idUser { get; set; }
        [Required]
        [Display(Name = "Nombre")]
        public string vName { get; set; }
        public string vLastName { get; set; }
        public string vUserName { get; set; }
        public string vPassword { get; set; }
        public Nullable<bool> bActive { get; set; }
    }
}
